import { LisaFoodItem } from './types';
import { generateId } from '../utils/id';

export const predefinedLisaFoods: LisaFoodItem[] = [
  {
    id: 'lisa-nogo-weizen',
    name: 'Weizen',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Weizenmehl', 'Weizenstärke', 'Weizengluten', 'Hartweizen', 'Weizengrieß'],
  },
  {
    id: 'lisa-nogo-dinkel',
    name: 'Dinkel',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Dinkelmehl', 'Dinkelflocken'],
  },
  {
    id: 'lisa-nogo-gerste',
    name: 'Gerste',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Gerstenmalz', 'Gerstenmalzextrakt', 'Gerstenflocken'],
  },
  {
    id: 'lisa-nogo-roggen',
    name: 'Roggen',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Roggenmehl', 'Roggenvollkornmehl'],
  },
  {
    id: 'lisa-nogo-leinsamen',
    name: 'Leinsamen',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: [],
  },
  {
    id: 'lisa-nogo-kamut',
    name: 'Kamut',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Khorasan-Weizen', 'Khorasan'],
  },
  {
    id: 'lisa-nogo-kaffee',
    name: 'Kaffee',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Coffee', 'Koffein', 'Coffein'],
  },
  {
    id: 'lisa-nogo-ingwer',
    name: 'Ingwer',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: [],
  },
  {
    id: 'lisa-nogo-milch',
    name: 'Milch (Kuh)',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Kuhmilch', 'Milch', 'Magermilchpulver', 'Vollmilchpulver', 'Milchpulver', 'Molke', 'Molkenpulver', 'Milcheiweiß', 'Milchprotein', 'Sahne', 'Butter'],
  },
  {
    id: 'lisa-nogo-ricotta',
    name: 'Ricotte (Kuh)',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Ricotta', 'Ricotta Kuhmilch', 'Ricotta aus Kuhmilch'],
  },
  {
    id: 'lisa-nogo-eidotter',
    name: 'Hühnereidotter',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Eigelb', 'Hühnereigelb', 'Eidotter'],
  },
  {
    id: 'lisa-nogo-eiweiss',
    name: 'Hühnereiweiß',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Eiweiß', 'Eiklar', 'Hühnereiweiss', 'Albumin'],
  },
  {
    id: 'lisa-nogo-wachtelei',
    name: 'Wachtelei',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Wachteleier'],
  },
  {
    id: 'lisa-nogo-gaenseei',
    name: 'Gänseei',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Gänseeier'],
  },
  {
    id: 'lisa-nogo-sonnenblumenkern',
    name: 'Sonnenblumenkern',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Sonnenblumenkerne'],
  },
  {
    id: 'lisa-nogo-sonnenblumenoel',
    name: 'Sonnenblumenöl',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Sonnenblumenoel', 'Sunflower Oil'],
  },
  {
    id: 'lisa-nogo-mandel',
    name: 'Mandel',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Mandeln', 'Mandelmehl', 'Mandelmus', 'Mandelprotein'],
  },
  {
    id: 'lisa-nogo-haselnuss',
    name: 'Haselnuss',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Haselnüsse', 'Haselnuesse', 'Haselnussmus', 'Haselnussmark'],
  },
  {
    id: 'lisa-nogo-erdnuss',
    name: 'Erdnuss',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ['Erdnüsse', 'Erdnuesse', 'Erdnussbutter', 'Erdnussöl', 'Erdnussoel', 'Peanut', 'Peanuts'],
  },

  // Example Happy Foods for initial MVP testing
  {
    id: 'lisa-happy-zucker',
    name: 'Zucker',
    category: 'Süßungsmittel',
    status: 'happy',
    aliases: ['Rohrzucker', 'Rübenzucker'],
  },
  {
    id: 'lisa-happy-kakao',
    name: 'Kakaobutter',
    category: 'Sonstiges & Spezial',
    status: 'happy',
    aliases: ['Kakao', 'Kakaomasse'],
  },
  {
    id: 'lisa-happy-soja',
    name: 'Sojalecithin',
    category: 'Sonstiges & Spezial',
    status: 'happy',
    aliases: ['Soja', 'Sojabohnen'],
  }
];

export const lisaCategories = [
  'Das gar nicht',
  'Getreide, Pseudogetreide, Stärkehaltiges',
  'Hülsenfrüchte',
  'Nüsse & Samen',
  'Wurzel- & Knollengemüse',
  'Pilze',
  'Blattgemüse',
  'Zwiebelgemüse',
  'Kohlgemüse',
  'Fruchtgemüse',
  'Kern- und Steinobst',
  'Beeren & Melone',
  'Milchprodukte',
  'Süßungsmittel',
  'Fleisch & Wild',
  'Fisch & Meeresfrüchte',
  'Sonstiges & Spezial',
  'Kräuter & Gewürze',
  'Verdickungsmittel',
  'Getränke / Extrakte'
];
