import { LisaFoodItem } from './types';

export const predefinedLisaFoods: LisaFoodItem[] = [
  {
    id: 'lisa-nogo-gluten',
    name: 'Gluten',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["glutenhaltiges getreide", "glutenhaltig"],
  },
  {
    id: 'lisa-nogo-dinkel',
    name: 'Dinkel',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["dinkelmehl", "dinkelflocken"],
  },
  {
    id: 'lisa-nogo-gerste',
    name: 'Gerste',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["gerstenmalz", "gerstenmalzextrakt", "gerstenflocken"],
  },
  {
    id: 'lisa-nogo-roggen',
    name: 'Roggen',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["roggenmehl", "roggenvollkornmehl"],
  },
  {
    id: 'lisa-nogo-weizen',
    name: 'Weizen',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["weizenmehl", "weizenstärke", "weizengluten", "hartweizen", "weizengrieß", "weizenkleber"],
  },
  {
    id: 'lisa-nogo-leinsamen',
    name: 'Leinsamen',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: [],
  },
  {
    id: 'lisa-nogo-kamut',
    name: 'Kamut',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["khorasan-weizen", "khorasan"],
  },
  {
    id: 'lisa-nogo-kaffee',
    name: 'Kaffee',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["coffee", "koffein", "coffein"],
  },
  {
    id: 'lisa-nogo-ingwer',
    name: 'Ingwer',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: [],
  },
  {
    id: 'lisa-nogo-milch-kuh',
    name: 'Milch (Kuh)',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["kuhmilch", "milch", "magermilchpulver", "vollmilchpulver", "milchpulver", "molke", "molkenpulver", "milcheiweiß", "milchprotein", "sahne", "butter", "rahm"],
  },
  {
    id: 'lisa-nogo-ricotte-kuh',
    name: 'Ricotte (Kuh)',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["ricotta", "ricotta kuhmilch", "ricotta aus kuhmilch"],
  },
  {
    id: 'lisa-nogo-h-hnereidotter',
    name: 'Hühnereidotter',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["eigelb", "hühnereigelb", "eidotter"],
  },
  {
    id: 'lisa-nogo-h-hnereiwei',
    name: 'Hühnereiweiß',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["eiweiß", "eiweiss", "eiklar", "hühnereiweiss", "hühnereiweiß", "albumin"],
  },
  {
    id: 'lisa-nogo-wachtelei',
    name: 'Wachtelei',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["wachteleier"],
  },
  {
    id: 'lisa-nogo-g-nseei',
    name: 'Gänseei',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["gänseeier"],
  },
  {
    id: 'lisa-nogo-sonnenblumenkern',
    name: 'Sonnenblumenkern',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["sonnenblumenkerne"],
  },
  {
    id: 'lisa-nogo-sonnenblumen-l',
    name: 'Sonnenblumenöl',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["sonnenblumenoel", "sunflower oil"],
  },
  {
    id: 'lisa-nogo-mandel',
    name: 'Mandel',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["mandeln", "mandelmehl", "mandelmus", "mandelprotein"],
  },
  {
    id: 'lisa-nogo-haselnuss',
    name: 'Haselnuss',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["haselnüsse", "haselnuesse", "haselnussmus", "haselnussmark"],
  },
  {
    id: 'lisa-nogo-erdnuss',
    name: 'Erdnuss',
    category: 'Das gar nicht',
    status: 'no_go',
    aliases: ["erdnüsse", "erdnuesse", "erdnussbutter", "erdnussöl", "erdnussoel", "peanut", "peanuts"],
  },
  {
    id: 'lisa-happy-amaranth',
    name: 'Amaranth',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-buchweizen',
    name: 'Buchweizen',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-fonio',
    name: 'Fonio',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-guarkernmehl-e-412',
    name: 'Guarkernmehl (E 412)',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: ["guarkernmehl", "e412"],
  },
  {
    id: 'lisa-happy-hafer-glutenfrei',
    name: 'Hafer (glutenfrei)',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-hirse',
    name: 'Hirse',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kichererbse',
    name: 'Kichererbse',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-linse',
    name: 'Linse',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-mais',
    name: 'Mais',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-quinoa',
    name: 'Quinoa',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-reis',
    name: 'Reis',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-tapioka',
    name: 'Tapioka',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-teff',
    name: 'Teff',
    category: 'Getreide, Pseudogetreide, Stärkehaltiges',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-bohne-gr-n-dick',
    name: 'Bohne (grün/dick)',
    category: 'Hülsenfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-erbse',
    name: 'Erbse',
    category: 'Hülsenfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kichererbse',
    name: 'Kichererbse',
    category: 'Hülsenfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-linse',
    name: 'Linse',
    category: 'Hülsenfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-mungobohne',
    name: 'Mungobohne',
    category: 'Hülsenfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-cashewkerne',
    name: 'Cashewkerne',
    category: 'Nüsse & Samen',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-esskastanie',
    name: 'Esskastanie',
    category: 'Nüsse & Samen',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-hagebutte',
    name: 'Hagebutte',
    category: 'Nüsse & Samen',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kokosnuss',
    name: 'Kokosnuss',
    category: 'Nüsse & Samen',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-k-rbiskerne',
    name: 'Kürbiskerne',
    category: 'Nüsse & Samen',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-macadamia',
    name: 'Macadamia',
    category: 'Nüsse & Samen',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-paranuss',
    name: 'Paranuss',
    category: 'Nüsse & Samen',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-pekannuss',
    name: 'Pekannuss',
    category: 'Nüsse & Samen',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-pinienkerne',
    name: 'Pinienkerne',
    category: 'Nüsse & Samen',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-pistazie',
    name: 'Pistazie',
    category: 'Nüsse & Samen',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-karotte',
    name: 'Karotte',
    category: 'Wurzel- & Knollengemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kartoffel',
    name: 'Kartoffel',
    category: 'Wurzel- & Knollengemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-k-rbis-kerne',
    name: 'Kürbis/Kerne',
    category: 'Wurzel- & Knollengemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-maniok',
    name: 'Maniok',
    category: 'Wurzel- & Knollengemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-pastinake',
    name: 'Pastinake',
    category: 'Wurzel- & Knollengemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-rote-beete',
    name: 'Rote Beete',
    category: 'Wurzel- & Knollengemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-sellerieknolle',
    name: 'Sellerieknolle',
    category: 'Wurzel- & Knollengemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-s-kartoffel',
    name: 'Süßkartoffel',
    category: 'Wurzel- & Knollengemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-austernspilz',
    name: 'Austernspilz',
    category: 'Pilze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-champignon',
    name: 'Champignon',
    category: 'Pilze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-maronen-r-hrling',
    name: 'Maronen-Röhrling',
    category: 'Pilze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-pfifferling',
    name: 'Pfifferling',
    category: 'Pilze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-artischocke',
    name: 'Artischocke',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-chinakohl',
    name: 'Chinakohl',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-chicor-e',
    name: 'Chicorée',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-endivie',
    name: 'Endivie',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-eisbergsalat',
    name: 'Eisbergsalat',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-feldsalat',
    name: 'Feldsalat',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-gartenkresse',
    name: 'Gartenkresse',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kopfsalat',
    name: 'Kopfsalat',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-lollo-rosso',
    name: 'Lollo Rosso',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-l-wenzahn',
    name: 'Löwenzahn',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-mangold',
    name: 'Mangold',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-radicchio',
    name: 'Radicchio',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-romanasalat',
    name: 'Romanasalat',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-rucola',
    name: 'Rucola',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-weinbl-tter',
    name: 'Weinblätter',
    category: 'Blattgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-b-rlauch',
    name: 'Bärlauch',
    category: 'Zwiebelgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-bleichsellerie',
    name: 'Bleichsellerie',
    category: 'Zwiebelgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-fenchel',
    name: 'Fenchel',
    category: 'Zwiebelgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-knoblauch',
    name: 'Knoblauch',
    category: 'Zwiebelgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-lauch',
    name: 'Lauch',
    category: 'Zwiebelgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-pastinake',
    name: 'Pastinake',
    category: 'Zwiebelgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-rote-beete',
    name: 'Rote Beete',
    category: 'Zwiebelgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-sellerieknolle',
    name: 'Sellerieknolle',
    category: 'Zwiebelgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-steckr-be',
    name: 'Steckrübe',
    category: 'Zwiebelgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-topinambur',
    name: 'Topinambur',
    category: 'Zwiebelgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-zwiebel',
    name: 'Zwiebel',
    category: 'Zwiebelgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-blumenkohl',
    name: 'Blumenkohl',
    category: 'Kohlgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-brokkoli',
    name: 'Brokkoli',
    category: 'Kohlgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-gr-nkohl',
    name: 'Grünkohl',
    category: 'Kohlgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kohlrabi',
    name: 'Kohlrabi',
    category: 'Kohlgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-radieschen',
    name: 'Radieschen',
    category: 'Kohlgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-rotkohl',
    name: 'Rotkohl',
    category: 'Kohlgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-rosenkohl',
    name: 'Rosenkohl',
    category: 'Kohlgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-wei-kohl',
    name: 'Weißkohl',
    category: 'Kohlgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-wirsing',
    name: 'Wirsing',
    category: 'Kohlgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-gurke',
    name: 'Gurke',
    category: 'Fruchtgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-k-rbis',
    name: 'Kürbis',
    category: 'Fruchtgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-muskatk-rbis',
    name: 'Muskatkürbis',
    category: 'Fruchtgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-okraschote',
    name: 'Okraschote',
    category: 'Fruchtgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-oliven',
    name: 'Oliven',
    category: 'Fruchtgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-paprikaschote',
    name: 'Paprikaschote',
    category: 'Fruchtgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-spargel',
    name: 'Spargel',
    category: 'Fruchtgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-zucchini',
    name: 'Zucchini',
    category: 'Fruchtgemüse',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-apfel',
    name: 'Apfel',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-aprikose',
    name: 'Aprikose',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-birne',
    name: 'Birne',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-dattel',
    name: 'Dattel',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-feige',
    name: 'Feige',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-guave',
    name: 'Guave',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kaktusfeige',
    name: 'Kaktusfeige',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kirsche',
    name: 'Kirsche',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-litschi',
    name: 'Litschi',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-mango',
    name: 'Mango',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-mirabelle',
    name: 'Mirabelle',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-nektarine',
    name: 'Nektarine',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-pfirsich',
    name: 'Pfirsich',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-pflaume',
    name: 'Pflaume',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-quitte',
    name: 'Quitte',
    category: 'Kern- und Steinobst',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-blaubeere',
    name: 'Blaubeere',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: ["heidelbeere", "heidelbeeren", "blaubeeren"],
  },
  {
    id: 'lisa-happy-heidelbeere',
    name: 'Heidelbeere',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-brombeere',
    name: 'Brombeere',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-cranberry',
    name: 'Cranberry',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-granatapfel',
    name: 'Granatapfel',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-honigmelone',
    name: 'Honigmelone',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-johannisbeere',
    name: 'Johannisbeere',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-preiselbeere',
    name: 'Preiselbeere',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-sanddorn',
    name: 'Sanddorn',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-stachelbeere',
    name: 'Stachelbeere',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-traube',
    name: 'Traube',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: ["weintraube", "weintrauben", "rosine", "rosinen"],
  },
  {
    id: 'lisa-happy-rosine',
    name: 'Rosine',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-wassermelone',
    name: 'Wassermelone',
    category: 'Beeren & Melone',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-halloumi',
    name: 'Halloumi',
    category: 'Milchprodukte',
    status: 'happy',
    aliases: ["hellim"],
  },
  {
    id: 'lisa-happy-hellim',
    name: 'Hellim',
    category: 'Milchprodukte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kamelmilch',
    name: 'Kamelmilch',
    category: 'Milchprodukte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kefir-kuh',
    name: 'Kefir (Kuh)',
    category: 'Milchprodukte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-milch-kuh-gekocht',
    name: 'Milch (Kuh, gekocht)',
    category: 'Milchprodukte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-schafsmilch',
    name: 'Schafsmilch',
    category: 'Milchprodukte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-schafsk-se',
    name: 'Schafskäse',
    category: 'Milchprodukte',
    status: 'happy',
    aliases: ["schafmilchkäse"],
  },
  {
    id: 'lisa-happy-stutenmilch',
    name: 'Stutenmilch',
    category: 'Milchprodukte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-ziegenmilch',
    name: 'Ziegenmilch',
    category: 'Milchprodukte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-ziegenk-se',
    name: 'Ziegenkäse',
    category: 'Milchprodukte',
    status: 'happy',
    aliases: ["ziegenmilchkäse"],
  },
  {
    id: 'lisa-happy-agavendicksaft',
    name: 'Agavendicksaft',
    category: 'Süßungsmittel',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-ahornsirup',
    name: 'Ahornsirup',
    category: 'Süßungsmittel',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-carob-pulver',
    name: 'Carob-Pulver',
    category: 'Süßungsmittel',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-dattelsirup',
    name: 'Dattelsirup',
    category: 'Süßungsmittel',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-honig',
    name: 'Honig',
    category: 'Süßungsmittel',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-rohrzucker',
    name: 'Rohrzucker',
    category: 'Süßungsmittel',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-vanille',
    name: 'Vanille',
    category: 'Süßungsmittel',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-ente',
    name: 'Ente',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-gans',
    name: 'Gans',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-hase',
    name: 'Hase',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-hirsch',
    name: 'Hirsch',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-huhn',
    name: 'Huhn',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kalb',
    name: 'Kalb',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kaninchen',
    name: 'Kaninchen',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-lamm',
    name: 'Lamm',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-reh',
    name: 'Reh',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-rind',
    name: 'Rind',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-strau',
    name: 'Strauß',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-truthahn',
    name: 'Truthahn',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-pute',
    name: 'Pute',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-wachtel',
    name: 'Wachtel',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-wildschwein',
    name: 'Wildschwein',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-ziege',
    name: 'Ziege',
    category: 'Fleisch & Wild',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-aal',
    name: 'Aal',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-blaualge-spirulina',
    name: 'Blaualge: Spirulina',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-dorade',
    name: 'Dorade',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-forelle',
    name: 'Forelle',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-hai',
    name: 'Hai',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-heilbutt',
    name: 'Heilbutt',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-hering',
    name: 'Hering',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kabeljau',
    name: 'Kabeljau',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-karpfen',
    name: 'Karpfen',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-lachs',
    name: 'Lachs',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-pangasius',
    name: 'Pangasius',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-red-snapper',
    name: 'Red Snapper',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-rotalge-nori',
    name: 'Rotalge: Nori',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-rotbarsch',
    name: 'Rotbarsch',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-schellfisch',
    name: 'Schellfisch',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-scholle',
    name: 'Scholle',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-schwertfisch',
    name: 'Schwertfisch',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-see-wolfsbarsch',
    name: 'See-/Wolfsbarsch',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-seehecht',
    name: 'Seehecht',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-seelachs',
    name: 'Seelachs',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-seezunge',
    name: 'Seezunge',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-seeteufel',
    name: 'Seeteufel',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-zander',
    name: 'Zander',
    category: 'Fisch & Meeresfrüchte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-alfalfa',
    name: 'Alfalfa',
    category: 'Sonstiges & Spezial',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-aloe-vera',
    name: 'Aloe Vera',
    category: 'Sonstiges & Spezial',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-bambussprossen',
    name: 'Bambussprossen',
    category: 'Sonstiges & Spezial',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kapern',
    name: 'Kapern',
    category: 'Sonstiges & Spezial',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-zitronenmelisse',
    name: 'Zitronenmelisse',
    category: 'Sonstiges & Spezial',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-anis',
    name: 'Anis',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-basilikum',
    name: 'Basilikum',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-bohnenkraut',
    name: 'Bohnenkraut',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-chilli-cayenne',
    name: 'Chilli Cayenne',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-chilli-jalapeno',
    name: 'Chilli Jalapeno',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-dill',
    name: 'Dill',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-estragon',
    name: 'Estragon',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-gartenkresse',
    name: 'Gartenkresse',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kardamom',
    name: 'Kardamom',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kerbel',
    name: 'Kerbel',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-koriander',
    name: 'Koriander',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-kreuzk-mmel',
    name: 'Kreuzkümmel',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-k-mmel',
    name: 'Kümmel',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-lavendel',
    name: 'Lavendel',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-liebst-ckel',
    name: 'Liebstöckel',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-lorbeerblatt',
    name: 'Lorbeerblatt',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-majoran',
    name: 'Majoran',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-mohn',
    name: 'Mohn',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-muskat',
    name: 'Muskat',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-muskatnuss',
    name: 'Muskatnuss',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-nelke',
    name: 'Nelke',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-oregano',
    name: 'Oregano',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-petersilie',
    name: 'Petersilie',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-piment',
    name: 'Piment',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-pfeffer-schwarz-wei',
    name: 'Pfeffer (schwarz/weiß)',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-pfefferminze',
    name: 'Pfefferminze',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-rosmarin',
    name: 'Rosmarin',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-salbei',
    name: 'Salbei',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-safran',
    name: 'Safran',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-salz',
    name: 'Salz',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-senfkorn',
    name: 'Senfkorn',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-selleriegr-n',
    name: 'Selleriegrün',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-thymian',
    name: 'Thymian',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-wacholder',
    name: 'Wacholder',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-zimt',
    name: 'Zimt',
    category: 'Kräuter & Gewürze',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-agar-agar-e-406',
    name: 'Agar-Agar (E 406)',
    category: 'Verdickungsmittel',
    status: 'happy',
    aliases: ["agar agar", "e406"],
  },
  {
    id: 'lisa-happy-guarkernmehl-e-412',
    name: 'Guarkernmehl (E 412)',
    category: 'Verdickungsmittel',
    status: 'happy',
    aliases: ["guarkernmehl", "e412"],
  },
  {
    id: 'lisa-happy-kurkumin-e-100',
    name: 'Kurkumin (E 100)',
    category: 'Verdickungsmittel',
    status: 'happy',
    aliases: ["curcumin", "kurkumaextrakt", "e100"],
  },
  {
    id: 'lisa-happy-pektin-e-440',
    name: 'Pektin (E 440)',
    category: 'Verdickungsmittel',
    status: 'happy',
    aliases: ["pektin", "e440"],
  },
  {
    id: 'lisa-happy-tragant-e-413',
    name: 'Tragant (E 413)',
    category: 'Verdickungsmittel',
    status: 'happy',
    aliases: ["e413"],
  },
  {
    id: 'lisa-happy-xanthan-e-415',
    name: 'Xanthan (E 415)',
    category: 'Verdickungsmittel',
    status: 'happy',
    aliases: ["xantan", "e415"],
  },
  {
    id: 'lisa-happy-kamille',
    name: 'Kamille',
    category: 'Getränke / Extrakte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-mohn',
    name: 'Mohn',
    category: 'Getränke / Extrakte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-tee-gr-n',
    name: 'Tee (grün)',
    category: 'Getränke / Extrakte',
    status: 'happy',
    aliases: ["grüner tee", "gruen tee", "green tea"],
  },
  {
    id: 'lisa-happy-tee-schwarz',
    name: 'Tee (schwarz)',
    category: 'Getränke / Extrakte',
    status: 'happy',
    aliases: ["schwarzer tee", "black tea"],
  },
  {
    id: 'lisa-happy-rotbusch',
    name: 'Rotbusch',
    category: 'Getränke / Extrakte',
    status: 'happy',
    aliases: ["rooibos", "rotbuschtee"],
  },
  {
    id: 'lisa-happy-rooibos',
    name: 'Rooibos',
    category: 'Getränke / Extrakte',
    status: 'happy',
    aliases: [],
  },
  {
    id: 'lisa-happy-sanddorn',
    name: 'Sanddorn',
    category: 'Getränke / Extrakte',
    status: 'happy',
    aliases: [],
  },
];

export const lisaCategories = [
  'Das gar nicht',
  'Getreide, Pseudogetreide, Stärkehaltiges',
  'Hülsenfrüchte',
  'Nüsse & Samen',
  'Wurzel- & Knollengemüse',
  'Pilze',
  'Blattgemüse',
  'Zwiebelgemüse',
  'Kohlgemüse',
  'Fruchtgemüse',
  'Kern- und Steinobst',
  'Beeren & Melone',
  'Milchprodukte',
  'Süßungsmittel',
  'Fleisch & Wild',
  'Fisch & Meeresfrüchte',
  'Sonstiges & Spezial',
  'Kräuter & Gewürze',
  'Verdickungsmittel',
  'Getränke / Extrakte',
];
